### PR TITLE
Fix CommonJS and AMD module export

### LINKED ISSUE #2: Loading with RequireJS fails
The export code at the bottom of the module seems to be broken.  It seems it was not tested thoroughly enough in its final form.

### PR DESCRIPTION
**Pull request by joeyparrish**
Overwriting "exports" fails to export the thing.  Instead, overwrite
module.exports.

Also, the build script had the wrong name in the stand-alone module
argument to browserify.

Closes #2

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -326,11 +326,12 @@ class EmeEncryptionSchemePolyfillMediaKeySystemAccess {
  */
 EmeEncryptionSchemePolyfill.originalRMKSA_;
 
-// Support for CommonJS module format.
+// Support for CommonJS and AMD module formats.
 /** @suppress {undefinedVars} */
 (() => {
-  if (typeof exports !== 'undefined') {
+  // eslint-disable-next-line no-undef
```
Comment (TheModMaker) [inline index.js]: Alternatively you could declare that `module` is a global variable:
https://eslint.org/docs/user-guide/configuring#specifying-globals

Comment (joeyparrish) [reply index.js]: Nice!  Thanks for the tip.  Done.
