### PR TITLE
fix: Check if McEncryptionSchemePolyfill is installed

### LINKED ISSUE #16: MediaCapabilities polyfill can be installed twice, leading to infinite recursion
The EME part of the polyfill checks to make sure it isn't installed twice, but the MCap polyfill doesn't.  This leads to infinite recursion when the polyfill tries to call the original, but ends up calling itself.

### PR DESCRIPTION
**Pull request by michellezhuogg**
Closes #16 .

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -475,6 +479,9 @@ function guessSupportedScheme(keySystem) {
  * @return {boolean} True if browser natively supports encryptionScheme.
  */
 function hasEncryptionScheme(mediaKeySystemAccess) {
+  if (!mediaKeySystemAccess) {
```
Comment (joeyparrish) [inline index.js:482]: It seems like this would apply the workaround in cases where it shouldn't be, by giving a false negative for unsupported configs.  We should check for capabilities.supported or capabilities.keySystemAccess before calling this method.

File: index.js [hunk 2]
```diff
@@ -276,7 +280,8 @@ class McEncryptionSchemePolyfill {
         await McEncryptionSchemePolyfill.originalDecodingInfo_.call(
             this, requestedConfiguration);
 
-    if (!requestedConfiguration.keySystemConfiguration) {
+    if (!requestedConfiguration.keySystemConfiguration ||
+        capabilities.keySystemAccess) {
```
Comment (joeyparrish) [inline index.js:284]: This would have to be !capabilities.keySystemAccess.  Otherwise, the probe is skipped for any successful DRM content.

**Review by joeyparrish — CHANGES_REQUESTED** [review]

**Review by joeyparrish — APPROVED** [review]
